TYPE 
    StepEnum :  
    ( 
        POWER_OFF, 
        WAIT_POWER_OFF,
        POWERED_OFF,
        POWER_ON, 
        WAIT_POWER_ON,
        GET_SHUTTLE, 
        READY, 
        START_MOVEMENT, 
        WAIT_START_MOVEMENT,
        MOVING,
        STOPPING,
        WAIT_STOPPING,
        ERROR,
        RESET 
    ); 
END_TYPE